name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths:
      - 'docker-action/**'
      - '!.github/'
  workflow_dispatch:
jobs:
  test-docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./docker-action
        with:
          who-to-greet: '@dmitrytretyakov'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"